### ISSUE TITLE
Mirror update

### ISSUE THREAD

**Issue by GoToNightmare** [PlayFab/MpsSamples#27]
Latest mirror have breaking changes
https://github.com/vis2k/Mirror/releases

NetworkServer.RegisterHandler<T>
And messages changed to struct
struct OnServerConnectMessage : NetworkMessage

Would be cool if you update it, thanks!

**Comment by dgkanatsios** [comment]
hey, thanks for the heads-up! On my TODO list, however if you or anyone else would like to submit a PR, we'd be more than welcome!

**Comment by dominicmoret** [comment]
Came across the same issue. Would be nice to update, can't get it working at the moment

**Comment by BenjaminKobjolke** [comment]
I think this was still not fixes?
Because I tried to run the UnityServer project and I got some errors from Mirror

**Comment by dgkanatsios** [comment]
@BenjaminKobjolke you say it doesn't work with the version of Mirror currently in the MpsSamples repo? I started to work on it but got sidetracked, if anyone can answer my question [here](https://forum.unity.com/threads/mirror-open-source-networking-for-unity.425437/page-32#post-6896351), that would be really helpful. Thanks!

**Comment by GoToNightmare** [comment]
@dgkanatsios not tested
1) NetworkServer.RegisterHandler<OnReceiveAuthenticateMessage>(OnReceiveAuthenticate);
private void OnReceiveAuthenticate(NetworkConnection connection, OnReceiveAuthenticateMessage message)
public struct OnReceiveAuthenticateMessage : NetworkMessage
2) Why do u need `.ReadMessage<T>` ?

**Comment by BenjaminKobjolke** [comment]
> 
> 
> @BenjaminKobjolke you say it doesn't work with the version of Mirror currently in the MpsSamples repo? I started to work on it but got sidetracked, if anyone can answer my question [here](https://forum.unity.com/threads/mirror-open-source-networking-for-unity.425437/page-32#post-6896351), that would be really helpful. Thanks!

I did not test your complete project.
I just wanted to try out prefab and the first step was to create a server and upload it to prefab.
Since I already have a project that uses mirror I tried to add the scripts from your repository to my project.
That's when I got the errors. 

I then tried to downgrade my Mirror version by using the one from your repository.
But then I got errors in my scripts because my scripts already implement the latest functions of the newer Mirror version.

I tried the latest latest Mirror version from gitHub (v35.0.1) with your scripts,

**Comment by GoToNightmare** [comment]
> @BenjaminKobjolke you say it doesn't work with the version of Mirror currently in the MpsSamples repo? I started to work on it but got sidetracked, if anyone can answer my question [here](https://forum.unity.com/threads/mirror-open-source-networking-for-unity.425437/page-32#post-6896351), that would be really helpful. Thanks!

```
NetworkServer.RegisterHandler<ReceiveAuthenticateMessage>(OnReceiveAuthenticate);
```

```
public struct ReceiveAuthenticateMessage : NetworkMessage
{
	public string PlayFabId;
}
```

```
private void OnReceiveAuthenticate(NetworkConnection arg1, ReceiveAuthenticateMessage arg2)
{
	var conn = _connections.Find(c => c.ConnectionId == arg1.connectionId);
	if (conn != null)
	{
		conn.PlayFabId = arg2.PlayFabId;
		conn.IsAuthenticated = true;
		OnPlayerAdded.Invoke(arg2.PlayFabId);
	}
}
```

**Comment by dgkanatsios** [comment]
hey @GoToNightmare @BenjaminKobjolke @dominicmoret I just made #37, if you have time to take a look before merging, we'd really appreciate it :)

**Comment by dgkanatsios** [comment]
Merged, feel free to re-open if there are any issues, thank you all!
