### ISSUE TITLE
Most recent commit of Unity Client/Server is missing PlayFab SDK code

### ISSUE THREAD

**Issue by 9nhne** [PlayFab/MpsSamples#59]
I updated my project to the latest release of the Unity Sample, and noticed that all the PlayFab SDK code is missing. I've tried downloading it multiple times and on different devices - just incase of personal error - but to no avail. Please fix this asap, this may delay some from starting their project, thanks for your time.
<img width="1139" alt="Screen Shot 2022-04-13 at 3 47 37 AM" src="https://user-images.githubusercontent.com/72675952/163126553-e22be8d3-1d0c-473a-ad45-6c061be8a61d.png">

**Comment by dgkanatsios** [comment]
This is by design, in an effort to make the sample as lightweight as possible. 
you can download the PlayFab Unity SDK from here https://github.com/PlayFab/UnitySDK

We’ll make a PR soon to remove the .meta references that Unity places, apologies for the inconvenience.
