### ISSUE TITLE
Getting GSDK not found error when trying to build Openarena

### ISSUE THREAD

**Issue by anushabc** [PlayFab/MpsSamples#70]
Facing issue when trying to build Openarena,  please find the error message below

**Error Message** 

Unhandled Exception: Microsoft.Playfab.Gaming.GSDK.CSharp.GSDKInitializationException: GSDK file -  not found

OpenArena for Azure PlayFab Multiplayer Servers

   at Microsoft.Playfab.Gaming.GSDK.CSharp.InternalSdk.GetConfiguration()

   at Microsoft.Playfab.Gaming.GSDK.CSharp.InternalSdk.Start(Boolean debugLogs)

   at Microsoft.Playfab.Gaming.GSDK.CSharp.GameserverSDK.LogMessage(String message)

   at openarena.Program.Main(String[] args) in /source/Program.cs:line 19

**Comment by dgkanatsios** [comment]
Are you using LocalMultiplayerAgent when running OpenArena? This error message means that the GSDK cannot find the JSON initialization file, which is created when running either on LocalMultiplayerAgent or on the cloud

**Comment by anushabc** [comment]
I was able to resolve the issue using LocalMultiplayerAgent, but once the build is completed in PlayFab environment when I try accessing the server using the ip and port i get the below screen



![image](https://user-images.githubusercontent.com/66515706/187466347-308a78ea-08c7-4fa3-9d0e-8ea65190bbaf.png)

I have verified the configuration everything looks correct, when i use LocalMultiplayer Agent  i found no error and it shows the status as active

![image](https://user-images.githubusercontent.com/66515706/187467170-6726caed-303f-4a09-aac9-b3cc03432772.png)

**Comment by dgkanatsios** [comment]
how are you configuring the ports when uploading to PlayFab? Did you manage to connect locally?

**Comment by anushabc** [comment]
For the ports in PlayFab under network section  I have selected  UDP, port number as 27960, I haven't tried connecting locally, I am very new to this, let me know if there is anything I am missing

**Comment by nikawang** [comment]
Just trying some demos in [Thundernetes](https://playfab.github.io/thundernetes/howtos/usingwrapper.html). And I've got same issue while trying to use mpswrapper to start openarena..
![image](https://user-images.githubusercontent.com/4372694/187828681-80f6d759-f10f-4874-9fbd-e0068ea1a713.png)

I'm wondering the wrapper in this repo is just a demo or we can use this wrapper to start any other exsiting games..

**Comment by dgkanatsios** [comment]
The wrapper is a utility that integrates with GSDK and you can use it to launch any game. However, since the wrapper is integrated with GSDK, it expects to find the GSDK config file. This is only created when the wrapper is running on Thundernetes/MPS/LocalMultiplayerAgent.

**Comment by dgkanatsios** [comment]
For Thundernetes and OpenArena, we have already built it: https://github.com/PlayFab/thundernetes/blob/main/samples/openarena/sample.yaml
