### ISSUE TITLE
UNITYTLS_X509VERIFY_FATAL_ERROR on Linux server

### ISSUE THREAD

**Issue by MirkoSrsens** [PlayFab/MpsSamples#76]
If you get error in Unity that looks like this:

Curl error 35: Cert handshake failed. verify result: UNITYTLS_X509VERIFY_FATAL_ERROR. error state: 7\n","stream":"stdout","time":"2022-05-21T19:40:05.368326753Z"}
 
/Server/GetUserData: Unable to complete SSL connection\n","stream":"stdout","time":"2022-05-21T19:40:05.387915285Z"}

It means you are missing certificates which are not included when building image or the server. This dockerfile for unity: https://github.com/PlayFab/MpsSamples/blob/main/UnityMirror/Dockerfile should be modified to look like this

FROM ubuntu:20.04
WORKDIR /game
ADD . .
RUN apt update
RUN apt install -y --reinstall ca-certificates
EXPOSE 7777/udp 
CMD ["/game/Game.exe"]

which will install certificates inside the image and it should work (or at least remove that issue). EXOPOSE 7777/udp is not needed. Many ppl with no Linux experience will struggle to figure it out (as did I).

**Comment by dgkanatsios** [comment]
thanks @MirkoSrsens for reporting this. Any chance you can do a Pull Request on the README (maybe in this section https://github.com/PlayFab/MpsSamples/tree/main/UnityMirror#running-unity-server-as-a-linux-container) to add this valuable information?

**Comment by MirkoSrsens** [comment]
Will do!
